/**
 * Builds the fillable "Landseed Grant Application" template asset used by
 * src/backend/services/grantTemplateFill.ts (FR-3.2 Phase 2).
 *
 * There is no official grant-program template to source fields from, so
 * this template's sections/fields are derived directly from FR-3.2 ("...
 * pre-filled client and project details") and the fields already assembled
 * by src/backend/services/grantPdfAssembler.ts. Re-run this script (via
 * `npm run assets:generate-grant-template`) whenever the field set needs to
 * change; the output is a checked-in binary asset, not generated at runtime.
 */
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { writeFileSync } from "fs";
import { join } from "path";
import { GRANT_TEMPLATE_FIELD_NAMES } from "../src/backend/services/grantTemplateFields";

async function main() {
  const doc = await PDFDocument.create();
  const page = doc.addPage([612, 792]);
  const form = doc.getForm();
  const titleFont = await doc.embedFont(StandardFonts.HelveticaBold);
  const bodyFont = await doc.embedFont(StandardFonts.Helvetica);

  const marginX = 56;
  const fieldX = marginX + 190;
  const fieldWidth = 612 - fieldX - marginX;
  let y = 730;

  function drawTitle(text: string, size = 20) {
    page.drawText(text, { x: marginX, y, size, font: titleFont, color: rgb(0.11, 0.2, 0.37) });
    y -= size + 12;
  }

  function drawSubtitle(text: string) {
    page.drawText(text, { x: marginX, y, size: 9, font: bodyFont, color: rgb(0.4, 0.4, 0.4) });
    y -= 24;
  }

  function drawSectionHeader(text: string) {
    y -= 6;
    page.drawText(text, { x: marginX, y, size: 12, font: titleFont, color: rgb(0.11, 0.2, 0.37) });
    page.drawLine({
      start: { x: marginX, y: y - 4 },
      end: { x: 612 - marginX, y: y - 4 },
      thickness: 0.75,
      color: rgb(0.8, 0.82, 0.86),
    });
    y -= 22;
  }

  function drawField(label: string, fieldName: string, opts: { height?: number } = {}) {
    const height = opts.height ?? 18;
    page.drawText(`${label}:`, { x: marginX, y: y + 4, size: 10, font: bodyFont, color: rgb(0.2, 0.2, 0.2) });

    const textField = form.createTextField(fieldName);
    if (height > 18) {
      textField.enableMultiline();
    }
    textField.addToPage(page, {
      x: fieldX,
      y: y - (height - 18),
      width: fieldWidth,
      height,
      borderWidth: 0.75,
      borderColor: rgb(0.75, 0.75, 0.75),
    });
    textField.setFontSize(10);

    y -= height + 12;
  }

  drawTitle("Landseed Grant Application");
  drawSubtitle(
    "Pre-filled from project intake and eligibility assessment. Fields marked [Incomplete] require follow-up before submission."
  );

  drawSectionHeader("Applicant Information");
  drawField("Full Name", GRANT_TEMPLATE_FIELD_NAMES.applicantName);
  drawField("Email Address", GRANT_TEMPLATE_FIELD_NAMES.applicantEmail);
  drawField("Phone Number", GRANT_TEMPLATE_FIELD_NAMES.applicantPhone);

  drawSectionHeader("Property Information");
  drawField("Property Address", GRANT_TEMPLATE_FIELD_NAMES.projectAddress);
  drawField("Property Ownership Status", GRANT_TEMPLATE_FIELD_NAMES.ownershipStatus);

  drawSectionHeader("Project & Grant Details");
  drawField("Grant Program", GRANT_TEMPLATE_FIELD_NAMES.grantProgramName);
  drawField("Requested Modifications", GRANT_TEMPLATE_FIELD_NAMES.modificationItems, { height: 48 });
  drawField("Estimated Project Cost", GRANT_TEMPLATE_FIELD_NAMES.estimatedCost);

  drawSectionHeader("Administrative");
  drawField("Internal Project ID", GRANT_TEMPLATE_FIELD_NAMES.projectId);
  drawField("Date Prepared", GRANT_TEMPLATE_FIELD_NAMES.preparedDate);

  y -= 6;
  page.drawText("Incomplete Fields — Requires Follow-Up", {
    x: marginX,
    y,
    size: 12,
    font: titleFont,
    color: rgb(0.6, 0.1, 0.1),
  });
  page.drawLine({
    start: { x: marginX, y: y - 4 },
    end: { x: 612 - marginX, y: y - 4 },
    thickness: 0.75,
    color: rgb(0.8, 0.82, 0.86),
  });
  y -= 22;
  drawField("Incomplete Fields", GRANT_TEMPLATE_FIELD_NAMES.incompleteFields, { height: 40 });

  page.drawText(
    "Generated by Landseed InPlace. This document is a pre-filled aid and does not guarantee grant approval.",
    { x: marginX, y: 40, size: 8, font: bodyFont, color: rgb(0.5, 0.5, 0.5) }
  );

  const outPath = join(process.cwd(), "assets", "grant-templates", "grant-application-template.pdf");
  const bytes = await doc.save();
  writeFileSync(outPath, bytes);
  console.log(`Wrote grant application template to ${outPath}`);
}

main().catch((error) => {
  console.error("Failed to generate grant application template:", error);
  process.exit(1);
});
